### ISSUE TITLE
Cannot find kernel Get<T> method

### ISSUE THREAD

**Issue by BrainCrumbz** [ninject/Ninject.MockingKernel#23]
Hello all

I've installed Ninject.MockingKernel.NSubstitute v3.2.20 via Nuget, and all its related dependencies of course. I cannot seem to proceed on the very first basic step: getting an instance of class under test.

```c#
var kernel = new NSubstituteMockingKernel();

MyClassUnderTest component = kernel.Get<MyClassUnderTest>();
```

Get<T> method is not defined. I've also checked (closed) issue #14 , without any luck. I've checked source code here on Github, in this project and in Ninject project, but I could not understand where Get<T> is defined. Is that some extension method or what?

Thanks a lot

**Comment by scott-xu** [comment]
`using Ninject;`
