### ISSUE TITLE
Incorrect version dependency for Ninject.MockingKernel.Moq NuGet package

### ISSUE THREAD

**Issue by GitSnafu** [ninject/Ninject.MockingKernel#24]
Ninject.MockingKernel.Moq 3.2.2.0 appears to depend on Ninject.MockingKernel version 3.2.2.0 or above, but when downloading the former from NuGet Ninject.MockingKernel version 3.2.0.0 is installed. This may cause the following error: System.TypeLoadException : Could not load type 'Ninject.MockingKernel.AdditionalInterfaceParameter' from assembly 'Ninject.MockingKernel, Version=3.2.0.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7'.

As far as I can tell AdditionalInterfaceParameter isn't available in Ninject.MockingKernel 3.2.0.0. Upgrading to 3.2.2.0 fixes the issue.

**Comment by VioletTape** [comment]
Confirm that it's still exists and very frustrating. I've spent about an hour to realize that it's tool nut not my code

**Comment by cjames9001** [comment]
This is preventing my team from using this version, we either have to downgrade Ninject, Ninject.MockingKernel, and Ninject.MockingKernel.Moq to 3.0.1.10, 3.0.0.5, 3.0.0.5 respectively.

Please fix this versioning issue.

**Comment by caractacus** [comment]
This issue still exists on the current Nuget package versions.  Are we to assume this project is dead?

**Comment by scott-xu** [comment]
Please make sure you installed all the latest Ninject packages
