### ISSUE TITLE
Setup a mocked injected object

### ISSUE THREAD

**Issue by jeusdi** [ninject/Ninject.MockingKernel#30]
I've configured a `MockingKernel` in order to mock a dependency:

    [TestFixture]
    public class TestsFixture
    {
        private NSubstituteMockingKernel IoCKernel;

        public UsersTests()
        {
            this.IoCKernel = new NSubstituteMockingKernel();
        }

        [SetUp]
        public void SetUp()
        {
            this.IoCKernel.Reset();
        }

        [Test]
        public void AddUserTest()
        {
            var mock = this.IoCKernel.Bind<Core.Configuration.ICoreConfiguration>().ToMock();
            mock.Setup( <<<<<<< How to substitute methods of this mocked objects??????
                m =>
                m.UserIdentities
                    .Returns(new List<UserIdentity>() {new UserIdentity("user1")}
            );

            Core.Kernel coreKernel = this.IoCKernel.Get<Core.Kernel>();
        }
    }

According to [this documentation][1] I need to call a `Setup` method in order to substitute methods. Nevertheless, `Setup` method is not available.

Any ideas?

  [1]: https://github.com/ninject/Ninject.MockingKernel/wiki/Examples

**Comment by dvygolov** [comment]
You didn't read the example carefully! Look at this place:
```
//setup the mock
var barMock = _kernel.GetMock<IBar>();
barMock.Setup(mock => mock.GetContent()).Returns("mocked Content");
```

and here's your code:

```
var mock = this.IoCKernel.Bind<Core.Configuration.ICoreConfiguration>().ToMock();
mock.Setup(...);
```

You don't get the mock, you just declare the binding.

**Comment by jeusdi** [comment]
I'm about to suicide!

Currently:

    var mock = this.IoCKernel
        .Bind<Core.Configuration.ICoreConfiguration>()
        .ToMock();

Nevertheless compiler is getting me that `Setup` method is not available!!

**Comment by scott-xu** [comment]
Please use GetMock to get mock object.

**Comment by jeusdi** [comment]
`GetMock` is not available!!! Could you provide an example using NSubstituteMockingKernel? Which usings do I need to add?

**Comment by jeusdi** [comment]
I've tried this:

    //Setup Mocks
    Mock<Core.Configuration.ICoreConfiguration> mockedConfiguration = this.IoCKernel.GetMock<Core.Configuration.ICoreConfiguration>();
    mockedConfiguration.Setup(c => c.UserIdentities).Returns(configurationUsers);

    Mock<Core.Kernel> kernel = this.IoCKernel.GetMock<Core.Kernel>();  <<<<

on `<<<<<` it throws an `System.ArgumentException` with this message:

> Object instance was not created by Moq.

The stack trace is:

```
   at Moq.Mock.Get[T](T mocked)
   at Ninject.MockingKernel.Moq.MoqMockingKernel.GetMock[T]()
   at Tests.Kernel.Users.Moq.UsersManagementTests.InitializationWithUsersTest() in D:\projects\living\clients\NetCore\Tests.Kernel\Users\UsersTestsMoq.cs:line 41
```

Which is the difference between `MockingKernel.Get<T>` and `MockingKernel.GetMock()`?
