### ISSUE TITLE
Is able mocking a concrete class?

### ISSUE THREAD

**Issue by jeusdi** [ninject/Ninject.MockingKernel#32]
I've tried this:

    //Setup Mocks
    Mock<Core.Configuration.ICoreConfiguration> mockedConfiguration = this.IoCKernel.GetMock<Core.Configuration.ICoreConfiguration>();
    mockedConfiguration.Setup(c => c.UserIdentities).Returns(configurationUsers);

    Mock<Core.Kernel> kernel = this.IoCKernel.GetMock<Core.Kernel>();  <<<<

on `<<<<<` it throws an `System.ArgumentException` with this message:

> Object instance was not created by Moq.

The stack trace is:

```
   at Moq.Mock.Get[T](T mocked)
   at Ninject.MockingKernel.Moq.MoqMockingKernel.GetMock[T]()
   at Tests.Kernel.Users.Moq.UsersManagementTests.InitializationWithUsersTest() in D:\projects\living\clients\NetCore\Tests.Kernel\Users\UsersTestsMoq.cs:line 41
```

Which is the difference between `MockingKernel.Get<T>` and `MockingKernel.GetMock()`?

**Comment by jeusdi** [comment]
Could you help me using [this repository](https://github.com/jeusdi/MockingKernel)? I've also created a [gitter room](https://gitter.im/MockingKernel/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

**Comment by scott-xu** [comment]
You are using both Moq and Nsubstitute. Please choose one of them.
